test reports?

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -44,3 +44,9 @@ jobs:
           fi
           echo $COMMAND
           eval $COMMAND
+      - uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Test reports
+          path: reports/TEST-*.xml    # Path to test results
+          reporter: java-junit
